export const GET_DATA = 'GET_DATA';
export const SORT_ENTRIES = 'SORT_ENTRIES';
export const CLEAR_CURRENT_SORT = 'CLEAR_CURRENT_SORT';
export const SEARCH_PUBLICATIONS = 'SEARCH_PUBLICATIONS';
export const SET_LOADING = 'SET_LOADING';
export const ERROR = 'ERROR';
export const APPLY_FILTERS = 'APPLY_FILTERS';
export const SET_SELECT_FILTER = 'SET_SELECT_FILTER';
